services:
  flask-app:
    build: 
      context: ./src
      dockerfile: Dockerfile.dev
    ports:
      - 5500:5500
    volumes:
      - ".:/src/app"
    environment:
      - FLASK_ENV=development 
      - FLASK_APP=main.py  
    
    